eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name:  index-data
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: 47.103.223.78 # Redis服务器地址 （默认为127.0.0.1）
    port: 6379    # Redis服务器连接端口 （默认为6379）
    password: 123456   # Redis服务器连接密码（默认为空）
    timeout: 5000  # 连接超时时间（毫秒）
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
#开启eureka负载均衡策略
ribbon:
  eureka:
    enable: true